### PR TITLE
Update build type to enable resource shrinking 

### PR DESCRIPTION
**Pull request by jig08**
Updating build type as:
```
buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
```

Wrt Issue #331

### CODE REVIEW

**Comment by zassmin** [comment]
@jig08 this is helpful and can be merged. We also want the strings removed from the source.

**Comment by jig08** [comment]
@zassmin Sure, will work on it too :)

**Comment by zassmin** [comment]
:+1:

**Comment by shehbashahab** [comment]
Unused resource removal will be taken care of by #331

**Pull request merged**
