### PR TITLE
User Profile removed from back stack

### LINKED ISSUE #393: Sign Up Page Persists
After successful sign up, the screen to review your profile persists in the background even after successful submission and is accessed on pressing back from timeline.

### PR DESCRIPTION
**Pull request by chhavip**
Fixed #393.

### CODE REVIEW

**Comment by zassmin** [comment]
@chhavip thanks for submitting! I'm trying to review and seeing `unknown repository` as the branch you are submitting the PR against. I'm thinking it might appear that way because the branch isn't synced with master. Let me know.

**Comment by zassmin** [comment]
@chhavip let me know if I could help with this! Would love to get this merged in.

**Comment by chhavip** [comment]
@zassmin , no I got the problem, been swamped lately, will take care of this and other issues soon!

**Comment by chhavip** [comment]
@zassmin Have submitted a new PR at #405 .

**Pull request closed without merging**
