### PR TITLE
Adding '\' to precede an apostrophe

### PR DESCRIPTION
**Pull request by jig08**
Work on Issue #337

### CODE REVIEW

**Comment by zassmin** [comment]
@jig08 :+1: after you rebase against master.

**Comment by jig08** [comment]
Yes Yes.

**Comment by zassmin** [comment]
I see why there's a conflict it looks like @shehbashahab committed on master https://github.com/WomenWhoCode/WomenWhoCode/commit/2828763328977ea2437caf26fabcced62500dae7

**Comment by jig08** [comment]
Oh !
@zassmin So should I close this PR then ? The issue seems to have been resolved :)

**Comment by zassmin** [comment]
ya, sorry about that.

**Comment by jig08** [comment]
No issues .

**Pull request closed without merging**
